title: "Mamta Saini"
url: "https://mamtasaini003.github.io"
baseurl: ""  # For root-level deployment
theme: "al-folio"
description: "A personal website showcasing my research and projects in scientific machine learning."
author: "Mamta Saini"